# Generated by Django 3.1.7 on 2021-08-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heroe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Character', models.CharField(max_length=255)),
                ('Publisher', models.CharField(max_length=255)),
                ('Alter_ego', models.CharField(max_length=255)),
                ('First_appearence', models.CharField(max_length=255)),
                ('imagen', models.ImageField(upload_to='heroes')),
            ],
        ),
    ]
