# Generated by Django 3.1.7 on 2021-08-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroe',
            name='imagen',
            field=models.FileField(upload_to='heroes'),
        ),
    ]
