# Generated by Django 3.1.7 on 2021-08-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20210829_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroe',
            name='imagen',
            field=models.FileField(blank=True, default='media/logo192.png', null=True, upload_to='heroes'),
        ),
    ]
