# Generated by Django 3.1.7 on 2021-08-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_auto_20210829_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroe',
            name='imagen',
            field=models.FileField(default='media/logo192.png', upload_to='heroes'),
        ),
    ]
